### ISSUE TITLE
Error whe try to run "detect_emotions" method

### ISSUE THREAD

**Issue by lpostingher** [justinshenk/fer#13]
When I try to run this code, I have an exception

```
from fer import FER
import cv2 as cv

img = cv.imread(temp_file_name)
detector = FER()
detector.detect_emotions(img=img)
```

```
Traceback (most recent call last):
  File "c:/Dev/Python/vocacional-server/photo/emotion.py", line 17, in <module>
    detector.detect_emotions(img=img)
  File "C:\Users\lucas.postingher\AppData\Local\Programs\Python\Python36\lib\site-packages\fer\fer.py", line 236, in detect_emotions
    face_rectangles = self.find_faces(img, bgr=True)
  File "C:\Users\lucas.postingher\AppData\Local\Programs\Python\Python36\lib\site-packages\fer\fer.py", line 180, in find_faces
    if isinstance(self.__face_detector, cv2.CascadeClassifier):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by lpostingher** [comment]
I'm running on Windows. Python 3.6.1.

**Comment by justinshenk** [comment]
Hi Lucas, can you run python and see if your cv2 has a CascadeClassifier
method?

import cv2; print(cv2.CascadeClassifier)

**Comment by lpostingher** [comment]
Hi Justin, this is the output on my windows machine.

```
>>> import cv2
>>> print(cv2.CascadeClassifier)
<built-in function CascadeClassifier>
```

Today I tried to run the same script on my linux macinhe, and it works fine.

**Comment by justinshenk** [comment]
Interesting, it appears related to the Windows OpenCV build.

Can you please share the output of:

hasattr(cv2.CascadeClassifier, "detectMultiScale")

**Comment by lpostingher** [comment]
Sure.

```
>>> import cv2
>>> hasattr(cv2.CascadeClassifier, "detectMultiScale")
False
```

**Comment by justinshenk** [comment]
It's not clear to me what is different about your OpenCV library but I
expected CascadeClassifier would be a class, not a function.

A few more things to debug: print(cv2.__version__) and print(dir(cv2))

Are you able to follow these instructions for Face recognition:
https://www.datacamp.com/community/tutorials/face-detection-python-opencv?
Otherwise, we may have to find the appropriate pip file to install on
your system.
