### ISSUE TITLE
Paper used

### ISSUE THREAD

**Issue by Gauravajariwal11** [justinshenk/fer#14]
Hi, great work with the code. Just want to know what paper you have used, and is there any way that I can get the accuracy of this? Although in one of the closed issues, the accuracy was mentioned to be 66%. Another question that I have is: does it make a big difference in using MTCNN in the face detection rather than [this method](https://arxiv.org/pdf/1612.02903.pdf)?

**Comment by justinshenk** [comment]
Thanks! The model used is similar to the one described here:
https://medium.com/free-code-camp/facial-emotion-recognition-develop-a-c-n-n-and-break-into-kaggle-top-10-f618c024fa
<https://medium.com/free-code-camp/facial-emotion-recognition-develop-a-c-n-n-and-break-into-kaggle-top-10-f618c024faa7>

Hope that helps.

**Comment by Gauravajariwal11** [comment]
Thanks a lot @justinshenk
