### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by Roiinbarr** [justinshenk/fer#17]
line 302, in top_emotion
    top_emotion = top_emotions[0]
IndexError: list index out of range 

I am using the the top_emotion and detect_emotions functions but on some of the videos I get this Error, anything I can do to solve this ?

**Comment by justinshenk** [comment]
Can you share a video where that happens to shenkjustin@gmail.com?

**Comment by justinshenk** [comment]
Clsoing issue due to inactivity
