### ISSUE TITLE
can i install fer into ubuntu ??

### ISSUE THREAD

**Issue by Neel7317** [justinshenk/fer#27]
After install pip install fer in ubuntu and when my code is try to import that it shows me error that no module found please help me.

**Comment by justinshenk** [comment]
You should be able to. Try debugging it like any Python import error first:
https://stackoverflow.com/questions/2325923/how-to-fix-importerror-no-module-named-error-in-python
.

**Comment by Neel7317** [comment]
Thank you its solve.
