### ISSUE TITLE
Having trouble for importing the library

### ISSUE THREAD

**Issue by Mitibus** [justinshenk/fer#32]
Hi, 

I'm having some troubles while trying to use the library. I've installed it with the `pip install fer`. I have the following error while trying the example script : 
`ImportError: cannot import name 'FER' from partially initialized module 'fer' (most likely due to a circular import) (C:\Users\mxmdu\Desktop\Programmation\Python\FaceRecognizer\fer.py)`

The script 
```
from fer import FER
import cv2

img = cv2.imread("justin.jpg")
detector = FER()
detector.detect_emotions(img)

```

Python version : 3.9.7

**Comment by justinshenk** [comment]
If you have a file named fer.py in your directory it may cause some
troubles. Please try again in a different directory or rename the file.
