### ISSUE TITLE
video cropping

### ISSUE THREAD

**Issue by kingkw1** [justinshenk/fer#38]
I've encountered issues with using the detection_box argument in the Video.analyze() function. With a little digging, I've found that self._crop(frame, detection_box) results in the following error:

`{TypeError}_crop() missing 1 required positional argument: 'detection_box'`

This problem stems from the combination of a @staticmethod decorator and "self" as an input argument to the _crop() function, and can be resolved by removing the "self" input argument from the _crop function definition.
```

    @staticmethod
    def _crop(self, frame, detection_box):

```

For the time being I've gotten around this with a monkey patch:

```
from fer import Video
Video._crop = lambda self, frame, _detection_box: frame[
                                                  _detection_box.get("y_min"): _detection_box.get("y_max"),
                                                  _detection_box.get("x_min"): _detection_box.get("x_max")]
```

**Comment by justinshenk** [comment]
Thank you for opening this! This has been fixed in v22.0.1.
