### ISSUE TITLE
GPU usage of emotion classification

### ISSUE THREAD

**Issue by rafamestre** [justinshenk/fer#39]
Hi Justin,

Great project, it really is saving my life! I have a question about GPU usage (it's not really an issue, so sorry if this is not the right way to ask):

I'm using the detect_emotion() function providing already the bounding box of the faces, which come from previous data. I'm wondering, does the emotion classification part of the function use GPU acceleration? I've checked the source code and it's not clear to me, since it's using Tensorflow, which I know can support GPU directly in the recent versions. I know that face detection using mtcnn does use GPU acceleration, but I'm avoiding that part of the function by providing the bounding boxes.

In case it does use GPU acceleration to classify the emotions, I really don't think it provides any noteworthy improvements, since it's a very fast process and cannot be done in batches, am I right?

Thanks again!

**Comment by justinshenk** [comment]
I'm glad you find it useful! It will use a GPU if it is available. You can verify this with 

```python
import tensorflow as tf
tf.debugging.set_log_device_placement(
    enabled=True
)
```
Whether there is a performance improvement for using a GPU, probably not a lot. The biggest improvement would probably come from batching, as you suggested. This would be an additional feature, which would require a bit of refactoring but could be added. Let me know if this is important for your use case.

**Comment by rafamestre** [comment]
Hi Justin, I'm so sorry for the very late reply. For some reason I was not subscribed to this and didn't get the notification!

Thanks for the info. Just wanted to make sure I understood everything correctly. I guess batch recognition could be a nice feature, but it's definitely not important for my case, so don't worry about it. Thanks a lot for the offer though! The performance is already great as it is and it's not much of a bottleneck - CPU parallelisation gives fast results!

Thanks again!
