### ISSUE TITLE
Expression predicts unexpected error

### ISSUE THREAD

**Issue by zhouhao-learning** [justinshenk/fer#5]
Hello, I have another accidental bug when I tested your code. I executed `python example.py` and got the following error:
```
Traceback (most recent call last):
  File "/home/zh/sda1/人脸识别/微表情分析/fer/example.py", line 11, in <module>
    result = detector.detect_emotions(image)
  File "/home/zh/sda1/人脸识别/微表情分析/fer/src/fer/fer.py", line 250, in detect_emotions
    x1 = np.clip(x1, a_min=0)
TypeError: clip() missing 1 required positional argument: 'a_max'
```
My test picture is:
![恐惧2](https://user-images.githubusercontent.com/24581773/61423051-df3f9d00-a940-11e9-9778-12f21a7e423e.jpeg)

I think the fix for this bug is to modify the `detect_emotions` function of `fer.py`.
```
 def detect_emotions(self, img: np.ndarray) -> list:
        if img is None or not hasattr(img, "shape"):
            raise InvalidImage("Image not valid.")

        emotion_labels = self._get_labels()
        face_rectangles = self.find_faces(img, bgr=True)
        gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        emotions = []
        for face_coordinates in face_rectangles:
            face_coordinates = self.tosquare(face_coordinates)
            x1, x2, y1, y2 = self.__apply_offsets(face_coordinates)

            if y1 < 0 or x1 < 0:
                gray_img = self.pad(gray_img)
                x1 += 40
                x2 += 40
                y1 += 40
                y2 += 40
                x1 = np.clip(x1, a_min=0,a_max=0)
                y1 = np.clip(y1, a_min=0,a_max=0)

```
Do you agree?

Another problem is that when I set `mtcnn=True`, I will encounter a situation where I can't detect the face:
```
Traceback (most recent call last):
  File "/home/zh/sda1/人脸识别/微表情分析/fer/example.py", line 14, in <module>
    bounding_box = result[0]["box"]
IndexError: list index out of range
```
So is `mtcnn` not accurate enough, not recommended?
The test image I am using is:
![成龙1](https://user-images.githubusercontent.com/24581773/61423910-33984c00-a944-11e9-8a50-6ed4884ecbd8.jpeg)

In addition, I also found other problems. If there are multiple faces in my picture, `mtcnn=True` can detect multiple faces, `mtcnn=False` can only detect one face.

**Comment by justinshenk** [comment]
Thanks a lot for your comments!

You are correct about the missing `a_max` parameter. That is fixed in `v19.0.5.dev2`. 

Regarding the Jackie Chan face, I also was not able to detect it with `mtcnn=True`, but otherwise it appears to be working. Perhaps mtcnn doesn't work well on images specifically like this?

Regarding detecting multiple faces, this is probably a bug to fix, although not sure where it is happening.

**Comment by justinshenk** [comment]
For your first test picture (only with mtcnn) I get:

`[OrderedDict([('box', (36, -2, 169, 169)), ('emotions', {'angry': 0.14, 'disgust': 0.0, 'fear': 0.83, 'happy': 0.0, 'sad': 0.0, 'surprise': 0.02, 'neutral': 0.0})])]`

**Comment by zhouhao-learning** [comment]
> Thanks a lot for your comments!
> 
> You are correct about the missing `a_max` parameter. That is fixed in `v19.0.5.dev2`.
> 
> Regarding the Jackie Chan face, I also was not able to detect it with `mtcnn=True`, but otherwise it appears to be working. Perhaps mtcnn doesn't work well on images specifically like this?
> 
> Regarding not detecting multiple faces, this is probably a bug to fix, although not sure where it is happening.

@justinshenk 
Yes, if you have multiple faces, your code captures the expression of the first face. What I want to say is that mtcnn has a computational method to calculate which face is closest to the image center when multiple faces are detected, and then choose this face as the last face because of the work I have done. Only one face needs to be detected, so I use this method, the effect is as follows:
![justin_drawn](https://user-images.githubusercontent.com/24581773/61452162-bd203c00-a98d-11e9-9c16-9919150218be.jpg)


The calculation code is as follows:
```
bounding_boxes= self._mtcnn.detect_faces(img)
if len(bounding_boxes) > 1:
            faces_list = np.array([x["box"] for x in bounding_boxes])
            # 通过计算 bounding_box 大小 和 offset_dist 中心偏差得出图片的主人翁
            # bb越大，偏差越小 越有可能，拿到index 加入 det_arr
            bounding_box_size = (faces_list[:, 2] - faces_list[:, 0]) * (faces_list[:, 3] - faces_list[:, 1])
            img_center = img_size / 2
            offsets = np.vstack([(faces_list[:, 0] + faces_list[:, 2]) / 2 - img_center[1],
                                 (faces_list[:, 1] + faces_list[:, 3]) / 2 - img_center[0]])
            offset_dist_squared = np.sum(np.power(offsets, 2.0), 0)
            index = np.argmax(
                bounding_box_size - offset_dist_squared * 2.0)
            faces= [faces_list[index].tolist()]
```

I hope it will be helpful to you. Of course, I support the method of displaying the emotions of multiple faces with multiple faces.

**Comment by justinshenk** [comment]
Thank you for sharing your solution!

**Comment by MIPromis** [comment]
from this type of output : **_**[OrderedDict([('box', (205, 109, 226, 226)), ('emotions', {'angry': 0.0, 'disgust': 0.0, 'fear': 0.0, 'happy': 0.0, 'sad': 0.01, 'surprise': 0.01, 'neutral': 0.97})])]**_**

How can I iterate through it in order to find separate emotions with their separate scores ?

**Comment by justinshenk** [comment]
```
for face in output:
  box = face['box']
  emotions = face['emotions']
    for emotion, score in emotions.items():
      print(emotion, score)
```

**Comment by MIPromis** [comment]
Thank you abundantly

**Comment by justinshenk** [comment]
You’re welcome!
