### ISSUE TITLE
Accuracy about the model

### ISSUE THREAD

**Issue by bruce0715** [justinshenk/fer#6]
Hi justin,

Great work! I wonder do you have the accuracy result when you train the data? thanks.

**Comment by bruce0715** [comment]
And could you also provide the architecture of the network using for the emotion recognition model.

**Comment by justinshenk** [comment]
I think the test accuracy for FER2013 is 66% and the bundled architecture is defined here: https://github.com/oarriaga/face_classification/blob/master/src/models/cnn.py.

**Comment by justinshenk** [comment]
Closing issue.
